name: candies_lints
description: The plugin to help create custom lint quickly.
version: 1.0.0
homepage: https://github.com/fluttercandies/candies_lints

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  analyzer: ^4.7.0
  analyzer_plugin: ^0.11.1
  logger: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: any

executables:
  candies_lints: main

# dart pub global activate --source path ./